Repository 00-pi/grpc-demo, pull requests merged in 2020-06, with the labels that each got.

#1 initial commit
  .gitignore
  README.md
  src/client/Console/Console.csproj
  src/client/Console/Console.csproj.user
  src/client/Console/Program.cs
  src/client/Console/Protos/tweet.proto
  src/grpc-demo.sln
  src/server/TweetService/Program.cs
  src/server/TweetService/Properties/launchSettings.json
  src/server/TweetService/Protos/tweet.proto
  src/server/TweetService/Services/TweeterService.cs
  src/server/TweetService/Startup.cs
  src/server/TweetService/TweetService.csproj
  src/server/TweetService/appsettings.Development.json
  src/server/TweetService/appsettings.json
Labels: enhancement

#2 Cleanup
  .vscode/launch.json
  .vscode/tasks.json
  grpc-demo.sln
  readme.md
  src/client/Console/Program.cs
  src/server/TweetService/Program.cs
  src/server/TweetService/Services/TweeterService.cs
  src/server/TweetService/Startup.cs
Labels: documentation

#3 remove dev appsettings
  .gitignore
  src/server/TweetService/appsettings.Development.json
Labels: bug

#4 stream tweets from twitter
  src/client/Console/Program.cs
  src/server/TweetService/Options/TwitterOAuthOptions.cs
  src/server/TweetService/Services/TweeterService.cs
  src/server/TweetService/Startup.cs
  src/server/TweetService/TweetService.csproj
Labels: enhancement
